# Config file for Stage 1 - Data Entry

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage01_data_entry'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'IDIBAPS'

# Name of stage output file.
STAGE_OUTPUT: "IDIBAPS_data.nix"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: 'nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    #IDIBAPS_161101_rec07_RH: '/home/rgutzen/Sciebo/own/Data/WaveScalES/IDIBAPS/TestData-for-SWAP_WT/161101_rec07_Spontaneous_RH.smr'
    #IDIBAPS_1: '/Users/andrew/Data/WaveScalES/hbp-01853_WBS/data-originals/WBS/WT/cond-WBS_type-WT_sub-1/hbp-01853_cond-WBS_type-WT_sub-1_chs-16_area-V1_hem-RH_ana-K100M13_stim-SPN.smr'
    #IDIBAPS_2: '/Users/andrew/Data/WaveScalES/hbp-01853_WBS/data-originals/WBS/WT/cond-WBS_type-WT_sub-1/hbp-01853_cond-WBS_type-WT_sub-1_chs-32_area-ALL_hem-RH_ana-K100M13_stim-SPN.smr'
    #IDIBAPS_type_WT_sub_1_chs_32_area_ALL_hem_RH_ana_K100M13_stim_SPN: 'https://object.cscs.ch/v1/AUTH_25b4e28a742d4987a7b6f84c0c36512e/hbp-01853_WBS/data-originals/WBS/WT/cond-WBS_type-WT_sub-1/hbp-01853_cond-WBS_type-WT_sub-1_chs-32_area-ALL_hem-RH_ana-K100M13_stim-SPN.smr'
    #IDIBAPS_type_WT_sub_5_chs_32_area_ALL_hem_RH_ana_K75M13_stim_SPN: 'https://object.cscs.ch/v1/AUTH_25b4e28a742d4987a7b6f84c0c36512e/hbp-01853_WBS/data-originals/WBS/WT/cond-WBS_type-WT_sub-5/hbp-01853_cond-WBS_type-WT_sub-5_chs-32_area-ALL_hem-RH_ana-K75M13_stim-SPN.smr'
    IDIBAPS_type_WT_sub_5_chs_32_area_ALL_hem_RH_ana_K75M13_stim_SPN: '/Users/andrew/Data/WaveScalES/hbp-01853_WBS/data-originals/WBS/WT/cond-WBS_type-WT_sub-5/hbp-01853_cond-WBS_type-WT_sub-5_chs-32_area-ALL_hem-RH_ana-K75M13_stim-SPN.smr'
    #IDIBAPS_3: 'https://object.cscs.ch/v1/AUTH_25b4e28a742d4987a7b6f84c0c36512e/hbp-01853_WBS/data-originals/WBS/WT/cond-WBS_type-WT_sub-2/hbp-01853_cond-WBS_type-WT_sub-2_chs-16_area-M1_hem-RH_ana-K75M13_stim-SPN.smr'
CURATION_SCRIPT: 'curate_IDIBAPS_data.py'

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [1,2,3]  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: 'png'

# pixel size
SPATIAL_SCALE: 0.55  # mm

# specified in the data file
SAMPLING_RATE: 'None' # Hz

# time slice in s
# if None, the entire recording is used
T_START: None
T_STOP: None

# Metadata
ANNOTATIONS:
    experimental_lab: 'Sanchez-Vives lab - Barcelona'
    grid_size: [9,5]
    anesthetic: 'Isoflurane'

ARRAY_ANNOTATIONS: 'None'

# The keyword arguments are passed as key value pairs.
# Keywords must only contain letters, numbers, underscores, and spaces.
# Values can be strings, int, float, bool, or None.
# Values can also be aranged in 1D objects such as lists, or tuples
# It is possible to specify nested subdict.
KWARGS:
    ELECTRODE_ANNOTATION_NAME: 'physical_channel_index'
    NAME2COORDS:
        0:  (0,1)
        1:  (6,4)
        2:  (3,3)
        3:  (4,3)
        4:  (5,3)
        5:  (6,3)
        6:  (7,3)
        7:  (8,3)
        8:  (1,2)
        9:  (2,2)
        10: (3,2)
        11: (4,2)
        12: (5,2)
        13: (6,2)
        14: (7,2)
        15: (8,2)
        16: (7,0)
        17: (1,1)
        18: (2,1)
        19: (3,1)
        20: (4,1)
        21: (5,1)
        22: (6,1)
        23: (7,1)
        24: (8,1)
        25: (0,0)
        26: (1,0)
        27: (2,0)
        28: (3,0)
        29: (4,0)
        30: (5,0)
        31: (6,0)
    ELECTRODE_LOCATION:
        Visual Cortex: [1,4,5,6,7,12,13,14,15,21,22,23,24]
        Retrospenial Cortex: [16,31,30,29]
        Parietal Association Cortex: [3,11,20]
        Somatosensory Cortex: [2,8,9,10,17,18,19]
        Motor Cortex: [0,25,26,27,28]
    ELECTRODE_COLOR: # color scheme to match to figures in publication
        Visual Cortex: '#0C6BB1'
        Retrospenial Cortex: '#422F58'
        Parietal Association Cortex: '#01B24E'
        Somatosensory Cortex: '#F92600'
        Motor Cortex: '#EF6700'

# dictionary mapping the channels (ELECTRODE_ANNOTATION_NAME) to their coordiantes on the grid (grid_size)
